name: Build and Push Add-on

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Add-on Version from config.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' addons/accuweather_mqtt/config.json)
          echo "ADDON_VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./addons/accuweather_mqtt/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/shockwave9315/accuweather-mqtt-addon:${{ steps.get_version.outputs.ADDON_VERSION }}
          build-args: |
            BUILD_FROM=homeassistant/amd64-base:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.description=Home Assistant Add-on: AccuWeather MQTT Publisher
            org.opencontainers.image.version=${{ steps.get_version.outputs.ADDON_VERSION }}

      - name: Make container image public
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/packages/container/accuweather-mqtt-addon/visibility \
            -d '{"visibility":"public"}'
