- name: Build and push Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ./addons/accuweather_mqtt/
          platforms: linux/${{ matrix.arch }}
          push: true
          # KLUCZOWA ZMIANA PONIŻEJ: tagujemy BEZ ARCHITEKTURY w nazwie obrazu
          tags: ghcr.io/shockwave9315/accuweather-mqtt-addon:${{ steps.get_version.outputs.ADDON_VERSION }}
          # Buildx automatycznie dodaje tagi architektoniczne do manifestu
          build-args: |
            BUILD_FROM=${{ matrix.build_from }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.description=Home Assistant Add-on: AccuWeather MQTT Publisher
            org.opencontainers.image.version=${{ steps.get_version.outputs.ADDON_VERSION }}
