name: Build and Push Add-on

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: # DODAJ TĘ SEKCJE - WAŻNE DLA BŁĘDU 403 Forbidden
      contents: read # Potrzebne do checkout
      packages: write # Potrzebne do pushowania obrazów do GHCR
    strategy:
      matrix:
        include:
          - arch: amd64
            build_from: homeassistant/amd64-base:latest
          - arch: arm64
            build_from: homeassistant/aarch64-base:latest
          - arch: armv7
            build_from: homeassistant/armv7-base:latest
          - arch: armhf
            build_from: homeassistant/armhf-base:latest
          - arch: i386
            build_from: homeassistant/i386-base:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Add-on Version from config.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' addons/accuweather_mqtt/config.json)
          echo "ADDON_VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ./addons/accuweather_mqtt/
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ghcr.io/shockwave9315/accuweather-mqtt-addon_${{ matrix.arch }}:${{ steps.get_version.outputs.ADDON_VERSION }}
          build-args: |
            BUILD_FROM=${{ matrix.build_from }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.description=Home Assistant Add-on: AccuWeather MQTT Publisher
            org.opencontainers.image.version=${{ steps.get_version.outputs.ADDON_VERSION }}

      - name: Make package public (IMPORTANT!)
        if: success() && matrix.arch == 'amd64' # Tylko raz, po udanym zbudowaniu choćby jednej arch.
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/packages/container/accuweather-mqtt-addon \
          -d '{"visibility": "public"}'
